import type { Metadata } from "next";
import "./globals.css";
import Providers from "./components/providers";
import ProvidersLayout from "./components/ProvidersLayout";

export const metadata: Metadata = {
  title: "WeWIN IELTS",
  description: "Generated by WeWIN Education",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full" suppressHydrationWarning>
      <body
        className="antialiased bg-[#F9FAFB] flex flex-col min-h-screen"
        suppressHydrationWarning
      >
        {/* ✅ Wrap toàn app trong SessionProvider */}
        <Providers>
          <ProvidersLayout>{children}</ProvidersLayout>
        </Providers>
      </body>
    </html>
  );
}
